const Notest = [
    {
        name : "세종스포츠정형외과",
        doctor: "김진수",
        location: '어린이대공원역',
	location_ : 0,
        part: '발목',
	part_: 1,
        descripiton: "전거비인대&종비인대 터지면 봉합가능",
        lat: 37.551736,
        lng:	127.075733,
	hospital: 'http://www.sjsportshospital.com/',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
    {
        name : "연세한강병원",
        doctor: "최우진",
        location: '마포역',
	location_ : 0,
        part: '발목',
	part_: 1,
        descripiton: "-",
        lat: 37.539893,
        lng:	126.944735,
	hospital: 'http://healthjoint.co.kr/',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
    {
        name : "연세건우병원",
        doctor: "박의현",
        location: '서울대입구역',
	location_ : 0,
        part: '발목',
	part_: 1,
        descripiton: "발목연골 문제까지 가능",
        lat: 37.481753,
        lng:	126.951378,
	hospital: 'http://www.healthyfriend.co.kr',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
    {
        name : "은평성모병원 정형외과",
        doctor: "이주엽",
        location: '구파발역',
	location_ : 0,
        part: '손목',
	part_: 0,
        descripiton: "수술 병원",
        lat: 37.635016,
        lng:	126.916997,
	hospital: 'https://www.cmcep.or.kr/page/main',
    	cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
    
    {
        name : "고려대안산병원 정형외과",
        doctor: "강종우",
        location: '안산 고잔역',
	location_ : 1,
        part: '손목',
	part_: 0,
        descripiton: "수술 병원",
        lat: 37.319175,
        lng: 126.825056,
	hospital: 'http://ansan.kumc.or.kr/main/index.do',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
    {
        name : "상무병원 정형외과",
        doctor: "박용철",
        location: '전라도 광주',
	location_ : 2,
        part: '손목',
	part_: 0,
        descripiton: "수술 병원 & 현장접수만 가능(선착순)",
        lat: 35.154013,
        lng: 126.853521,
	hospital: 'http://www.sangmoohospital.co.kr',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
    
    {
        name : "CM충무병원 정형외과",
        doctor: "이상훈",
        location: '영등포시장역',
	location_ : 0,
        part: '어깨',
	part_: 2,
        descripiton: "-",
        lat: 37.518815,
        lng: 126.903812,
	hospital: 'http://www.cmhospital.co.kr',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
    {
        name : "청담우리들 신경외과",
        doctor: "장원석, 이상호",
        location: '청담역',
	location_ : 0,
        part: '목',
	part_: 5,
        descripiton: "-",
        lat: 37.519212,
        lng: 127.049699,
	hospital: 'https://gangnam.wooridul.co.kr/',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
{
        name : "청담우리들 신경외과",
        doctor: "장원석, 이상호",
        location: '청담역',
	location_ : 0,
        part: '허리',
	part_: 3,
        descripiton: "-",
        lat: 37.519212,
        lng: 127.049699,
	hospital: 'https://gangnam.wooridul.co.kr/',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
    {
        name : "창원제일종합병원 신경외과",
        doctor: "윤석환",
        location: '마산창원',
	location_ : 3,
        part: '목',
	part_: 5,
        descripiton: "-",
        lat: 35.199941,
        lng: 128.567901, 
	hospital: 'http://www.mjeilh.co.kr',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
{
        name : "창원제일종합병원 신경외과",
        doctor: "윤석환",
        location: '마산창원',
	location_ : 3,
        part: '허리',
	part_: 3,
        descripiton: "-",
        lat: 35.199941,
        lng: 128.567901, 
	hospital: 'http://www.mjeilh.co.kr',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
    {
        name : "올바른서울병원 정형외과",
        doctor: "조재호",
        location: '서울 굽은다리역과 길동역 사이',
	location_ : 0,
        part: '무릎',
	part_: 4,
        descripiton: "-",
        lat: 37.542292,
        lng: 127.141293,
	hospital: 'http://www.allbarunhospital.co.kr',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
    {
        name : "연세더바른병원 정형외과",
        doctor: "권제호",
        location: '김포 구래역',
	location_ : 1,
        part: '무릎',
	part_: 4,
        descripiton: "-",
        lat: 37.645900,
        lng: 126.623725,
	hospital: 'http://www.ysthebareun.com',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
    {
        name : "청주마디사랑병원 정형외과",
        doctor: "변재용",
        location: '청주',
	location_ : 4,
        part: '무릎',
	part_: 4,
        descripiton: "-",
        lat: 36.638509,
        lng: 127.490371,
	hospital: 'http://www.madisarang.kr',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
    {
        name : "건재활의학과",
        doctor: "김병희",
        location: "강남역",
	location_ : 0,
        part: '재활의학과 및 마취통증의학과',
	part_: 7,
        descripiton: "-",
        lat: 37.492427,
        lng: 127.028692,
	hospital: 'http://www.kunrm.com',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
    {
        name : "삼성S마취통증의학과",
        doctor: "박해남",
        location: '수원 인계역',
	location_ : 1,
        part: '재활의학과 및 마취통증의학과',
	part_: 7,
        descripiton: "힐트레이저 HIRO 3.0 보유",
        lat: 37.262303,
        lng: 127.031189,
	hospital: 'http://www.samsungpain.com',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
    {
        name : "온누리통증의학과",
        doctor: '-',
        location: "부산 용호동",
	location_ : 3,
        part: '재활의학과 및 마취통증의학과',
	part_: 7,
        descripiton: "PDRN 초음파 보면서 주사치료",
        lat: 35.119149,
        lng: 129.112102,
	hospital: '',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
    {
        name : "디스코한의원",
        doctor: '-',
        location: "부천",
	location_ : 1,
        part: '관절 척추 한의원(봉독, 도침, 화침 신경손상한약, etc)',
	part_: 7,
        descripiton: "관절 척추 한의원(봉독, 도침, 화침 신경손상한약, etc)",
        lat: 37.505541,
        lng: 126.753843,
	hospital: 'http://www.disc8275.com',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
    {
        name : "류마나우 한의원",
        doctor: '-',
        location: "수원터미널 근처",
	location_ : 1,
        part: '관절 척추 한의원(봉독, 도침, 화침 신경손상한약, etc)',
	part_: 7,
        descripiton: "관절 척추 한의원(봉독, 도침, 화침 신경손상한약, etc)",
        lat: 37.249840,
        lng: 127.022693,
	hospital: 'rheuma-clinic.com',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
    {
        name : "양산 365데이 한의원",
        doctor: "-",
        location: "양산",
	location_ : 3,
        part: '관절 척추 한의원(봉독, 도침, 화침 신경손상한약, etc)',
	part_: 7,
        descripiton: "관절 척추 한의원(봉독, 도침, 화침 신경손상한약, etc)",
        lat: 35.310744,
        lng: 129.004790,
	hospital: 'https://yangsan365dayhani.com/',
        cafe : 'https://cafe.naver.com/01041200777',
	cafeName : '네이버 프롤로 카페'
    },
   
  {
        name : "강남세브란스병원",
        doctor: "김근수",
        location: '서울',
	location_ : 0,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.492759,
        lng: 127.046311,
	hospital: 'http://gs.iseverance.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L',
	cafeName: '네이버 건정공 카페'
    },
    {
        name : "강남세브란스병원",
        doctor: "진동규",
        location: '서울',
	location_ : 0,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.492759,
        lng: 127.046311,
	hospital: 'http://gs.iseverance.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L',
	cafeName: '네이버 건정공 카페'
    },
  {
        name : "강남세브란스병원",
        doctor: "석경수",
        location: '서울',
	location_ : 0,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.492759,
        lng: 127.046311,
	hospital: 'http://gs.iseverance.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L',
	cafeName: '네이버 건정공 카페'
    },
  {
        name : "서울아산병원",
        doctor: "이춘성",
        location: '서울',
	location_ : 0,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.526770,
        lng: 127.108353,
	hospital: 'http://www.amc.seoul.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L',
	cafeName: '네이버 건정공 카페'
    },
  {
        name : "신촌세브란스병원",
        doctor: "윤도흠",
        location: '서울',
	location_ : 0,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.562248,
        lng: 126.940960,
	hospital: 'http://sev.iseverance.com/index.asp',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L',
	cafeName: '네이버 건정공 카페'
    }, 
 {
        name : "삼성서울병원",
        doctor: "김은상",
        location: '서울',
	location_ : 0,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.488119,
        lng: 127.085543,
	hospital: 'http://www.samsunghospital.com',
       cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L',
	cafeName: '네이버 건정공 카페'
    },
 {
        name : "삼성서울병원",
        doctor: "이종서",
        location: '서울',
	location_ : 0,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.488119,
        lng: 127.085543,
	hospital: 'http://www.samsunghospital.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L',
	cafeName: '네이버 건정공 카페'
    },

 {
        name : "강동경의대병원",
        doctor: "김기택",
        location: '서울',
	location_ : 0,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.553463,
        lng: 127.157668,
	hospital: 'http://www.khnmc.or.kr/index.do',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L',
	cafeName: '네이버 건정공 카페'
    },
 {
        name : "우리들병원",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.518937,
        lng: 127.049721,
	hospital: 'http://www.wooridul.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L',
	cafeName: '네이버 건정공 카페'
    },
 {
        name : "21세기 병원",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.485181,
        lng: 127.015596,
	hospital: 'http://www.21spine.co.kr/?fbclid=IwAR3e7Ps19cmlU2KKX3bo50x-3hY3Loludx638qVB6rgRQCUAOOqkKpdEILY',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L',
	cafeName: '네이버 건정공 카페'
    },

 {
        name : "연세알찬병원",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.610685,
        lng: 126.917400,
	hospital: 'https://blog.naver.com/vpfmthsk95',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L',
	cafeName: '네이버 건정공 카페'
    },
 {
        name : "달려라병원",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.534066,
        lng: 127.140880,
	hospital: 'http://www.hospitalrun.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L',
	cafeName: '네이버 건정공 카페'
    },
 {
        name : "선수촌병원",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.511555,
        lng: 127.078986,
	hospital: 'http://www.sunsoochon.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L',
	cafeName: '네이버 건정공 카페'
    },
 {
        name : "본서부병원",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.600718,
        lng: 126.922562,
	hospital: 'http://www.bonseobu.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L',
	cafeName: '네이버 건정공 카페'
    },
 {
        name : "서울성심병원",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.584120,
        lng: 127.049816,
	hospital: 'http://www.sshosp.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "연세사랑병원",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.476692,
        lng: 126.986772,
	hospital: 'http://www.yonserang.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "활기찬정형외과",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.621109,
        lng: 126.919668,
	hospital: 'bone119.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "분당서울대병원",
        doctor: "염진섭",
        location: '경기',
	location_ : 1,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.352051,
        lng: 127.123190,
	hospital: 'http://www.snubh.org',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "일산백병원",
        doctor: "손문준",
        location: '경기',
	location_ : 1,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.674210,
        lng: 126.750350,
	hospital: 'http://www.paik.ac.kr/ilsan',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "의정부성모병원",
        doctor: "박종범",
        location: '경기',
	location_ : 1,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.758467,
        lng: 1127.077696,
	hospital: 'http://www.cmcujb.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "일산병원",
        doctor: "하중원",
        location: '경기',
	location_ : 1,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.645389,
        lng: 126.793017,
	hospital: 'http://www.nhimc.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "수원 윌스기념병원",
        doctor: "-",
        location: '경기',
	location_ : 1,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.265111,
        lng: 127.025467 ,
	hospital: 'http://www.allspine.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "분당 차병원",
        doctor: "-",
        location: '경기',
	location_ : 1,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.410890,
        lng: 127.126345,
	hospital: 'http://bundang.chamc.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "인천나누리병원",
        doctor: "-",
        location: '경기',
	location_ : 1,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.499451,
        lng: 126.730921,
	hospital: 'http://gs.nanoori.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "바른세상병원",
        doctor: "-",
        location: '경기',
	location_ : 1,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.410098,
        lng:  127.126848,
	hospital: 'http://www.barunsesang.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "이춘택병원",
        doctor: "-",
        location: '경기',
	location_ : 1,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.271991,
        lng: 127.015786,
	hospital: 'http://www.lct.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "국제성모병원",
        doctor: "진병호",
        location: '인천',
	location_ : 5,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.542392,
        lng: 126.683733,
	hospital: 'http://www.ish.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "인천성모병원",
        doctor: "-",
        location: '인천',
	location_ : 5,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.484747,
        lng: 126.724942,
	hospital: 'http://www.cmcism.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "우리들의원",
        doctor: "-",
        location: '인천',
	location_ : 5,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.499643,
        lng: 126.703837,
	hospital: '',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "부산백병원",
        doctor: "정용태",
        location: '부산',
	location_ : 3,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 35.146021,
        lng: 129.020883,
	hospital: 'http://www.paik.ac.kr/busan',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 
 
 {
        name : "해운대 부민병원",
        doctor: "-",
        location: '부산',
	location_ : 3,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 35.161405,
        lng: 129.155874,
	hospital: 'https://www.bumin.co.kr/haeundae/',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 
 {
        name : "계명대 동산의료원",
        doctor: "이석중",
        location: '경상도',
	location_ : 3,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 35.853460,
        lng: 128.480009,
	hospital: 'http://www.dsmc.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "척탑병원",
        doctor: "안성태 원장",
        location: '경상도',
	location_ : 3,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 35.865674,
        lng: 128.583033,
	hospital: 'http://www.topspine.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "보강병원",
        doctor: "-",
        location: '경상도',
	location_ : 3,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 35.813439,
        lng: 128.525324,
	hospital: 'http://www.bogang.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "보광병원",
        doctor: "-",
        location: '경상도',
	location_ : 3,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 35.836760,
        lng: 128.541705,
	hospital: 'http://www.bkhosp.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "창원삼성병원",
        doctor: "어환",
        location: '경상도',
	location_ : 3,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 35.242860,
        lng: 128.591902,
	hospital: 'https://smc.skku.edu:442/smc_main/main.smc',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "양산부산대병원",
        doctor: "-",
        location: '경상도',
	location_ : 3,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 35.327940,
        lng: 129.006511,
	hospital: 'http://www.pnuyh.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "을지대학교병원",
        doctor: "김환정",
        location: '대전,충청도',
	location_ : 4,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 36.355208,
        lng: 127.381890,
	hospital: 'http://www.emc.ac.kr/index.jsp',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "허리사랑병원",
        doctor: "-",
        location: '대전,충청도',
	location_ : 4,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 36.339596,
        lng: 127.390812,
	hospital: 'http://www.ilovespine.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "우리병원",
        doctor: "-",
        location: '대전,충청도',
	location_ : 4,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 36.343642,
        lng: 127.383780,
	hospital: 'http://www.woorispine.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 
 {
        name : "충북대학교병원",
        doctor: "이무섭",
        location: '대전,충청도',
	location_ : 4,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 36.623895,
        lng:  127.461463,
	hospital: 'http://www.cbnuh.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "한림대학교 춘천성심병원",
        doctor: "조용준",
        location: '강원도',
	location_ : 6,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 37.884038,
        lng: 127.739908,
	hospital: 'chuncheon.hallym.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "선한병원",
        doctor: "신호",
        location: '전라도',
	location_ : 2,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 35.161330,
        lng: 126.887177,
	hospital: 'http://www.shhospital.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "광주새우리병원",
        doctor: "-",
        location: '전라도',
	location_ : 2,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 35.153538,
        lng:  126.881426,
	hospital: 'http://www.saewoori.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "전북대학교병원",
        doctor: "은종필",
        location: '전라도',
	location_ : 2,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 35.847148,
        lng: 127.140638,
	hospital: 'http://www.jbuh.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "전남대학교병원",
        doctor: "이정길",
        location: '전라도',
	location_ : 2,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 35.141778,
        lng: 126.921685,
	hospital: 'https://www.cnuh.com/main.cs',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "원광대학교병원",
        doctor: "심대무",
        location: '전라도',
	location_ : 2,
        part: '허리', part_: 3,
        descripiton: "-",
        lat: 35.964327,
        lng: 126.959561,
	hospital: 'http://www.wkuh.org',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    
    
    {
        name : "건국대학교병원",
        doctor: "김진구 교수",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.540888,
        lng: 127.071904,
	hospital: 'http://www.kuh.ac.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    
    {
        name : "세브란스병원",
        doctor: "최종혁",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.562158,
        lng: 126.941060,
	hospital: 'http://sev.iseverance.com/index.asp',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "고려대안암병원",
        doctor: "장기모",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.587003,
        lng: 127.026528,
	hospital: 'http://anam.kumc.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "서울대학병원",
        doctor: "이명철",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.578585,
        lng: 126.997631,
	hospital: 'https://www.snuh.org/main.do',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "서울아산병원",
        doctor: "빈성일",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.526596,
        lng: 127.108479,
	hospital: 'http://www.amc.seoul.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "경희의료원",
        doctor: "윤경호",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.593886,
        lng: 127.051311,
	hospital: 'http://www.khuh.or.kr/',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "서울성심병원",
        doctor: "배대경",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.584147,
        lng: 127.049918,
	hospital: 'http://www.sshosp.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "바른세상병원",
        doctor: "임홍철",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.471315,
        lng: 126.897755,
	hospital: 'http://seoul.barunsesang.co.kr/',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "강남연세사랑병원",
        doctor: "김성재",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.476675,
        lng:  126.986692,
	hospital: 'http://www.yonserang.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "선수촌병원",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.511556,
        lng: 127.078949,
	hospital: 'http://www.sunsoochon.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "세바른병원",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.486297,
        lng: 127.015027,
	hospital: 'http://www.sebarun.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "올바른서울병원",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.542059,
        lng: 127.141341,
	hospital: 'http://www.allbarunhospital.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "본브릿지병원",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.515327,
        lng: 127.099495,
	hospital: 'http://www.bonbridgeos.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "달려라병원",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.534043,
        lng: 127.140895,
	hospital: 'http://www.hospitalrun.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "최원호병원",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.604881,
        lng: 126.923864,
	hospital: 'http://www.cwhhospital.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "케이에스병원",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.509271,
        lng: 127.043918,
	hospital: 'http://www.kshospital.net',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "연세알찬정형외과",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.610718,
        lng: 126.917353,
	hospital: 'http://alchanhospital.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "활기찬정형외과",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.621123,
        lng: 126.919713,
	hospital: 'http://bone119.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "정승기정형외과",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.610258,
        lng: 126.932039,
	hospital: 'http://www.drnopain.net',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "금메달정형외과",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.507164,
        lng: 127.022772,
	hospital: 'http://www.goldmedalclinic.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "종로기대찬의원",
        doctor: "-",
        location: '서울',
	location_ : 0,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.571060,
        lng: 126.980559,
	hospital: 'http://gm.gdc-hospital.co.kr/',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "아주대학병원",
        doctor: "민병현",
        location: '경기',
	location_ : 1,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.279379,
        lng: 127.047312,
	hospital: 'http://hosp.ajoumc.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "일산병원",
        doctor: "유주형",
        location: '경기',
	location_ : 1,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.645120,
        lng: 126.793142,
	hospital: 'http://www.nhimc.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "일산백병원",
        doctor: "나경욱",
        location: '경기',
	location_ : 1,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.674177,
        lng: 126.750333,
	hospital: 'http://www.paik.ac.kr/ilsan',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "남양주 현대병원",
        doctor: "정영복 부원장",
        location: '경기',
	location_ : 1,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.715346,
        lng: 127.179822,
	hospital: 'http://www.hdgh.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    
    {
        name : "분당차병원",
        doctor: "-",
        location: '경기',
	location_ : 1,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.410148,
        lng: 127.125503,
	hospital: 'http://bundang.chamc.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "일산21세기 병원",
        doctor: "-",
        location: '경기',
	location_ : 1,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.643950,
        lng: 126.786219,
	hospital: 'http://www.ilsan21.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "티케이정형외과",
        doctor: "-",
        location: '경기',
	location_ : 1,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.388042,
        lng: 127.114662,
	hospital: 'http://toptk.co.kr/main.php',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "이춘택병원",
        doctor: "-",
        location: '경기',
	location_ : 1,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.272022,
        lng: 127.015769,
	hospital: 'http://www.lct.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "경북대병원",
        doctor: "경희수",
        location: '대구',
	location_ : 3,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 35.866063,
        lng: 128.604800,
	hospital: 'https://www.knuh.kr/index.asp',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "더열린병원",
        doctor: "-",
        location: '대구',
	location_ : 3,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 35.852141,
        lng: 128.543418,
	hospital: 'http://www.theopen-daegu.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "한미병원",
        doctor: "-",
        location: '대구',
	location_ : 3,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 35.854826,
        lng: 128.511411,
	hospital: 'http://www.hanmihospital.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    
    {
        name : "천주성삼병원",
        doctor: "안혁수",
        location: '대구',
	location_ : 3,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 35.840233,
        lng: 128.705738,
	hospital: 'http://www.sungsam21.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    
    {
        name : "S&K병원",
        doctor: "김승기 원장",
        location: '대전',
	location_ : 4,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 36.348389,
        lng: 127.382602,
	hospital: 'http://www.skhospital.org',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "조재영정형외과의원",
        doctor: "-",
        location: '대전',
	location_ : 4,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 36.346443,
        lng: 127.386179,
	hospital: '',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "조인정형외과",
        doctor: "-",
        location: '대전',
	location_ : 4,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 36.343599,
        lng: 127.385496,
	hospital: 'http://www.joint-os.com/',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "인하대병원",
        doctor: "이진욱",
        location: '인천',
	location_ : 5,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.458793,
        lng: 126.634106,
	hospital: 'http://www.inha.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "부평힘찬병원",
        doctor: "이수찬",
        location: '인천',
	location_ : 5,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.492379,
        lng: 126.730146,
	hospital: 'http://himchanhospital.com/index.php/br/notice/27/br_cd/5',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "인천바로병원",
        doctor: "-",
        location: '인천',
	location_ : 5,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.450504,
        lng: 126.687529,
	hospital: 'http://www.baro119.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "부민병원",
        doctor: "서승석 원장",
        location: '부산 해운대',
	location_ : 3,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 37.556886,
        lng: 126.850935,
	hospital: 'https://www.bumin.co.kr/haeundae/',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "동의의료원",
        doctor: "김경택 원장",
        location: '부산',
	location_ : 3,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 35.169778,
        lng: 129.076744,
	hospital: 'http://www.demc.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "부산고려병원",
        doctor: "김인환 원장",
        location: '부산',
	location_ : 3,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 35.134752,
        lng: 129.092643,
	hospital: 'http://www.koreah.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "효성시티병원",
        doctor: "김종순 원장",
        location: '부산',
	location_ : 3,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 35.185201,
        lng: 129.121470,
	hospital: 'http://www.hshos.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "센텀병원",
        doctor: "-",
        location: '부산',
	location_ : 3,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 35.166297,
        lng: 129.114634,
	hospital: 'http://www.centumhospital.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    
    {
        name : "굿모닝병원",
        doctor: "-",
        location: '울산',
	location_ : 3,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 35.534961,
        lng: 129.319891,
	hospital: 'http://www.gm-hospital.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "빛고을전남대학교병원",
        doctor: "송은규",
        location: '광주',
	location_ : 2,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 35.094594,
        lng: 126.896156,
	hospital: 'https://www.cnubh.com/main.cs',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "세계로병원",
        doctor: "정재훈 원장",
        location: '광주',
	location_ : 2,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 35.191157,
        lng: 126.818589,
	hospital: 'http://www.segyero365.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "양산부산대학교병원",
        doctor: "신원철",
        location: '경상도',
	location_ : 3,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 35.327921,
        lng: 129.006508,
	hospital: 'http://www.pnuyh.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
    {
        name : "청주성모병원",
        doctor: "이기병 과장",
        location: '충청도',
	location_ : 4,
        part: '무릎', part_: 4,
        descripiton: "-",
        lat: 36.673656,
        lng: 127.485567,
	hospital: 'http://www.ccmc.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "서울대학교병원",
        doctor: "김세훈",
        location: '서울',
	location_ : 0,
        part: '어깨', part_: 2,
        descripiton: "-",
        lat: 37.579421,
        lng: 126.999198,
	hospital: 'http://www.snuh.org',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "세브란스병원",
        doctor: "천용민",
        location: '서울',
	location_ : 0,
        part: '어깨', part_: 2,
        descripiton: "-",
        lat: 37.562248,
        lng: 126.940960,
	hospital: 'http://sev.iseverance.com/index.asp',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 
 {
        name : "중앙대학교병원",
        doctor: "김재윤",
        location: '서울',
	location_ : 0,
        part: '어깨', part_: 2,
        descripiton: "-",
        lat: 37.506980,
        lng:  126.960550,
	hospital: 'http://ch.caumc.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 
 {
        name : "강남 서울성모병원",
        doctor: "유재철",
        location: '서울',
	location_ : 0,
        part: '어깨', part_: 2,
        descripiton: "-",
        lat: 37.501637,
        lng: 127.004817,
	hospital: 'http://www.cmcseoul.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "경희대학교병원",
        doctor: "이용걸",
        location: '서울',
	location_ : 0,
        part: '어깨', part_: 2,
        descripiton: "-",
        lat: 37.593849,
        lng: 127.051311,
	hospital: 'http://www.khuh.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 
 
 {
        name : "박진영 네온정형외과",
        doctor: "박진영",
        location: '서울',
	location_ : 0,
        part: '어깨', part_: 2,
        descripiton: "관절전문 병원",
        lat: 37.517906,
        lng: 127.040304,
	hospital: 'http://www.neon.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "달려라병원",
        doctor: "박재범",
        location: '서울',
	location_ : 0,
        part: '어깨', part_: 2,
        descripiton: "관절전문 병원",
        lat: 37.534076,
        lng: 127.140888,
	hospital: 'http://www.hospitalrun.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "마디병원",
        doctor: "김승호",
        location: '서울',
	location_ : 0,
        part: '어깨', part_: 2,
        descripiton: "관절전문 병원",
        lat: 37.517688,
        lng: 127.051105,
	hospital: 'http://madi.or.kr/main/ko/',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "CM충무병원",
        doctor: "이상훈",
        location: '서울',
	location_ : 0,
        part: '어깨', part_: 2,
        descripiton: "관절전문 병원",
        lat: 37.518770,
        lng: 126.903764,
	hospital: 'http://www.cmhospital.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "연세사랑병원",
        doctor: "김성재",
        location: '서울',
	location_ : 0,
        part: '어깨', part_: 2,
        descripiton: "관절전문 병원",
        lat: 37.476669,
        lng: 126.986701,
	hospital: 'http://www.yonserang.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 
 {
        name : "길병원",
        doctor: "김영규",
        location: '인천',
	location_ : 5,
        part: '어깨', part_: 2,
        descripiton: "-",
        lat: 37.451623,
        lng: 126.709190,
	hospital: 'http://www.gilhospital.com',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },

 {
        name : "아주대학교병원",
        doctor: "이두형",
        location: '경기',
	location_ : 1,
        part: '어깨', part_: 2,
        descripiton: "-",
        lat: 37.279256,
        lng: 127.047533,
	hospital: 'http://hosp.ajoumc.or.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 
 
 {
        name : "단국대학교병원",
        doctor: "서중배",
        location: '충청도',
	location_ : 4,
        part: '어깨', part_: 2,
        descripiton: "-",
        lat: 36.841943,
        lng:  127.172701,
	hospital: 'http://www.dkuh.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "탄탄병원",
        doctor: "김경천",
        location: '대전',
	location_ : 4,
        part: '어깨', part_: 2,
        descripiton: "-",
        lat: 36.346291,
        lng: 127.385287,
	hospital: 'http://www.tthp.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 
 {
        name : "여수백병원",
        doctor: "-",
        location: '전남',
	location_ : 2,
        part: '어깨', part_: 2,
        descripiton: "-",
        lat: 34.752042,
        lng: 127.703481,
	hospital: 'http://www.100hosp.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "대구가톨릭병원",
        doctor: "최창혁",
        location: '대구',
	location_ : 3,
        part: '어깨', part_: 2,
        descripiton: "-",
        lat: 35.843486,
        lng: 128.567777,
	hospital: 'http://www.dcmc.co.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },
 {
        name : "울산대학교병원",
        doctor: "고상훈",
        location: '경남',
	location_ : 3,
        part: '어깨', part_: 2,
        descripiton: "-",
        lat: 35.519945,
        lng: 129.428987,
	hospital: 'http://www.uuh.ulsan.kr',
        cafe: 		'https://cafe.naver.com/newin?iframe_url=/ArticleList.nhn%3Fsearch.clubid=19891065%26search.menuid=597%26search.boardtype=L', cafeName: '네이버 건정공 카페'
    },

]

export {
    Notest
}

// Data 넣을때 필요 (대량)